### ISSUE TITLE
Question: Group by key

### ISSUE THREAD

**Issue by 1123** [aws-samples/aws-glue-samples#16]
First, thanks for the great work on AWS Glue. One question: Can I use AWS Glue to group by key, and store the results in distinct files on S3 as follows?

Sample data in an s3 bucket:

<pre>
{ "key1": "A", "key2": "1" }
{ "key1": "B", "key2", "3" }
{ "key1": "A", "key2", "2" }
{ "key1": "B", "key2", "4" }
</pre>

Expected result: 

file1: 

<pre>
{ "key1": "A", "key2": "1" }
{ "key1": "A", "key2", "2" }
</pre>

file2: 

<pre>
{ "key1": "B", "key2", "3" }
{ "key1": "B", "key2", "4" }
</pre>

This is what I tried: 

<pre>
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)
datasource0 = glueContext.create_dynamic_frame.from_catalog(
    database = "my_db", 
    table_name = "my_input_table", 
    transformation_ctx = "datasource0")
partitioned_dataframe = datasource0.toDF().repartition(2, "key1")
partitioned_dynamicframe = DynamicFrame.fromDF(
    partitioned_dataframe, 
    glueContext, 
    "partitioned_df")
datasink2 = glueContext.write_dynamic_frame.from_options(
    frame = partitioned_dynamicframe, 
    connection_type = "s3", 
    connection_options = {"path": "s3://my-result-bucket/sub-bucket"}, 
    format = "json", 
    transformation_ctx = "datasink2")
</pre>

Yet as the FAQ clearly state, there is no guarantee that data with different keys will end up in different partitions, hence they mal also end up in the same file. 

From the FAQ: 

<pre>
Note that while different records with the same value for this column 
will be assigned to the same partition, there is no guarantee that there 
will be a separate partition for each distinct value.
</pre>

So I guess there must be a different way to achieve this. Any ideas?

**Comment by mohitsax** [comment]
Thanks for trying AWS Glue. Here is a solution for your problem.

First, you can refer the following blog post on how to partition a dynamic frame into Hive-style s3 partitions based on key values: 

https://aws.amazon.com/blogs/big-data/work-with-partitioned-data-in-aws-glue/

glueContext.write_dynamic_frame.from_options(
    frame = datasource0, 
    connection_type = "s3", 
    connection_options = {"path": "s3://my-result-bucket/sub-bucket", "partitionKeys" : ["key1"]}, 
    format = "json", 
    transformation_ctx = "datasink2")

Now if you would like to coalesce all files in each of these written Hive-style partition into a single file, you can create another dynamic frame using the Grouping feature in Glue that could read a large number of files from these Hive-style partitions into a group:

https://docs.aws.amazon.com/glue/latest/dg/grouping-input-files.html

datasource1 = glueContext.create_dynamic_frame_from_options("s3", {'paths': ["s3://my-result-bucket/sub-bucket/"], "recurse": True, 'groupFiles': 'inPartition', 'groupSize': 1024 * 1024}, format="json")

Finally, you can write out this dynamic frame datasource1 out to individual s3 files, where each output file would be roughly the same as groupSize. Make sure that your groupSize is larger than the size of each Hive-style partition, so that you have exactly 1 file per Hive-style partition or key value.
