### ISSUE TITLE
Data cleaning with AWS Glue example - crawler fails to create table

### ISSUE THREAD

**Issue by jpbarto** [aws-samples/aws-glue-samples#3]
Using the CSV at s3://awsglue-datasets/examples/medicare/Medicare_Hospital_Provider.csv and a newly provisioned crawler fails to create any tables.  This was tested using Glue in the Oregon region.

**Comment by chakrib** [comment]
I am landing into same issue. Did you find a solution please?

**Comment by d-v-dlee** [comment]
Did anyone ever resolve this?

**Comment by moomindani** [comment]
We are sorry for not replying this. 

You might use the entire path `s3://awsglue-datasets/examples/medicare/Medicare_Hospital_Provider.csv` in crawler's include path.
Please use the path `s3://awsglue-datasets/examples/medicare/` instead.

I also made small fix to make it clear.
https://github.com/aws-samples/aws-glue-samples/commit/4cba520813385494337a03e4c238a062e4526383

If the issue still remains, we recommend to ask the question in AWS Forum instead of creating/updating an issue on GitHub.

Resolving.
