### ISSUE TITLE
How to connect to my AWS account

### ISSUE THREAD

**Issue by roshni0107** [aws-samples/aws-glue-samples#58]
Hi,

In the sample code I do not see where we are passing AWS Auth Key and Secret Key to connect to AWS. Can you tell from where I can add those details in order to run this code against my AWS instance.

Thanks.

**Comment by moomindani** [comment]
The sample codes are for Glue ETL jobs. ETL jobs uses the IAM role which is attached to the job itself. See details in the public document. https://docs.aws.amazon.com/glue/latest/dg/add-job.html

If you have any other questions, please ask in AWS Glue forum instead of creating issue in GitHub.
https://forums.aws.amazon.com/forum.jspa?forumID=262
